config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get 'pages/home'

  get 'new/games'

  get 'new/create'

  get 'new/destroy'

  get 'new/edit'

  get 'new/index'

  get 'new/new'

  get 'new/show'

  get 'new/update'

  resources :users
  resource :session

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

    has_many :games   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  private
  def authenticate
  	# binding.pry
    @current_user = User.find_by :id =>	 session[:user_id] if session[:user_id]
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def games
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def index
  end

  def new
  end

  def show
  end

  def update
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:user_id, :points, :score_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path( user )
    else
      flash[:notice] = "Invalid login, please try again."
      redirect_to login_path
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # @top_score = User.find( params[:id] ).scores.limit(1).order( "points DESC" )
    # @high_scores = Score.limit(3).order( "points DESC" )
    # @top_names = User.find( params[:id] ).
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id 
        # this opens up a new session when user is created
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Allow the following paramaters
    def user_params
      params.require(:user).permit(:email, :user_name, :user_id, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/create.html.erb
<h1>New#create</h1>
<p>Find me in app/views/new/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>New#destroy</h1>
<p>Find me in app/views/new/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>New#edit</h1>
<p>Find me in app/views/new/edit.html.erb</p>

app/views/games/games.html.erb
<h1>New#games</h1>
<p>Find me in app/views/new/games.html.erb</p>

app/views/games/index.html.erb
<h1>New#index</h1>
<p>Find me in app/views/new/index.html.erb</p>

app/views/games/new.html.erb
<h1>New#new</h1>
<h2>Login</h2>
<%= form_tag '/login' do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag 'Login to Tunr' %>
<% end %>

app/views/games/show.html.erb
<h1>New#show</h1>
<p>Find me in app/views/new/show.html.erb</p>

app/views/games/update.html.erb
<h1>New#update</h1>
<p>Find me in app/views/new/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>GameApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

	<nav>
	  <%= link_to 'Home', '/' %>
	  <% if @current_user.present? %>
	    <%= link_to "Edit profile", users_edit_path %>
	    <%= link_to "Logout #{ @current_user.name }", destroy_user_session_path, :method => 'delete', :data => { :confirm => 'Are you sure you wish to logout?' } %>
	  <% else %>
	    <%= link_to 'Create Account', new_user_path %>
	    <%= link_to 'Login', new_session_path %>
	  <% end %>
	</nav>
	<%= yield %>

	</body>
</html>

app/views/pages/home.html.erb
  <script type="text/javascript">
    
    window.onload = function() {

      //  Create your Phaser game and inject it into the gameContainer div.
      //  We did it in a window.onload event, but you can do it anywhere (requireJS load, anonymous function, jQuery dom ready, - whatever floats your boat)
      var game = new Phaser.Game(window.innerWidth, window.innerHeight, Phaser.AUTO, '');

      

      //  Add the States your game has.
      //  You don't have to do this in the html, it could be done in your Boot state too, but for simplicity I'll keep it here.
      game.state.add('Boot', JetpackPug.Boot);
      game.state.add('Preloader', JetpackPug.Preloader);
      game.state.add('MainMenu', JetpackPug.MainMenu);
      game.state.add('Game', JetpackPug.Game);

      //  Now start the Boot state.
      game.state.start('Boot');

    };
  </script>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ol>
<% end %>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<p id="users_index"><%= notice %></p>

<h1>Users Index</h1>


<% if @current_user %>
  <!-- SOMEONE IS ACTUALLY LOGGED IN -->
  <h1>LOGGED IN</h1>
  <%= @current_user.email %>
  <%= link_to("Log out #{ @current_user.user_name }", login_path, :method => :delete) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User name</th>
      <th>User</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.user_name %></td>
        <td><%= user.id %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create a New Player</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>  

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>  

  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<div class="wrapper">

<!-- 	<p id="notice"><%= notice %></p> -->

	<div class="title"></div>

	<% if @current_user %>
	  <!-- SOMEONE IS ACTUALLY LOGGED IN -->

	<!--   <%= @current_user.email %> -->
	  <h2><%= (" Hi #{ @current_user.user_name } ") %></h2>
	<% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>